### ISSUE TITLE
Redis3.0 Cluster issue

### ISSUE THREAD

**Issue by wushuicheng** [ran-jit/TomcatRedisClusterEnabledSessionManager#2]
public class RedisCacheFactory
{
	private static Log log = LogFactory.getLog(RedisCacheFactory.class);
	
	private static Properties properties;

	protected static ICacheUtils cacheUtils;

	public static synchronized ICacheUtils createInstance(Properties props) throws Exception {
		try {
			if (props != null && !props.isEmpty()) {
				properties = props;
				if (!Boolean.valueOf(properties.getProperty(RedisConstants.IS_CLUSTER_ENABLED, RedisConstants.DEFAULT_IS_CLUSTER_ENABLED))) {
					cacheUtils = new RedisCacheUtils(properties);
				} else {
					cacheUtils = new RedisClusterCacheUtils(properties);
				}
			}
		} catch (Exception e) {
			log.error("Error creating redis instance", e);
		}
		return cacheUtils;
	}

	public static synchronized ICacheUtils getInstance() {
		return cacheUtils;
	}
}

public class RedisClusterCacheUtils implements ICacheUtils
{
	private Log log = LogFactory.getLog(RedisClusterCacheUtils.class);

	public boolean available = false;

	private static int numRetries = 30;

	private RedisClusterManager clusterManager = null;

	private boolean isClusterEnabled;

	RedisClusterCacheUtils(Properties properties) throws Exception {
		try {
			clusterManager = RedisClusterManager.createInstance(properties);
		} catch (Exception e) {
			this.available = false;
			log.error("Exception initializing Redis cluster: " + e);
		}
		this.available = true;
	}

	@Override
	public boolean isAvailable() {
		return available;
	}

	@Override
	public void setByteArray(byte[] key, byte[] value) {
		int tries = 0;
		boolean sucess = false;
		do {
			tries++;
			try {
				if (key != null && value != null) {
					if (isClusterEnabled) {
						clusterManager.getJedis().set(key, value);
					}
				}
				sucess = true;
			} catch (JedisClusterMaxRedirectionsException | JedisConnectionException e) {
				log.error("Jedis connection failed, retrying..." + tries);
				waitforFailover();
			}
		} while (!sucess && tries <= numRetries);
	}

	@Override
	public Long setStringIfKeyNotExists(byte[] key, byte[] value) {
		int tries = 0;
		Long retVal = null;
		boolean sucess = false;
		do {
			tries++;
			try {
				if (key != null && value != null) {
					if (isClusterEnabled) {
						retVal = clusterManager.getJedis().setnx(key, value);
					}
				}
				sucess = true;
			} catch (JedisClusterMaxRedirectionsException | JedisConnectionException e) {
				log.error("Jedis connection failed, retrying..." + tries);
				waitforFailover();
			}
		} while (!sucess && tries <= numRetries);
		return retVal;
	}

	@Override
	public void expire(byte[] key, int ttl) {
		int tries = 0;
		boolean sucess = false;
		do {
			tries++;
			try {
				if (isClusterEnabled) {
					clusterManager.getJedis().expire(key, ttl);
				}
				sucess = true;
			} catch (JedisClusterMaxRedirectionsException | JedisConnectionException e) {
				log.error("Jedis connection failed, retrying..." + tries);
				waitforFailover();
			}
		} while (!sucess && tries <= numRetries);
	}

	@Override
	public byte[] getByteArray(String key) {
		int tries = 0;
		boolean sucess = false;
		byte[] array = new byte[1];
		do {
			tries++;
			try {
				if (key != null) {
					array = clusterManager.getJedis().get(key.getBytes());
				}
				sucess = true;
			} catch (JedisClusterMaxRedirectionsException | JedisConnectionException e) {
				log.error("Jedis connection failed, retrying..." + tries);
				waitforFailover();
			}
		} while (!sucess && tries <= numRetries);
		return array;
	}

	@Override
	public void deleteKey(String key) {
		int tries = 0;
		boolean sucess = false;
		do {
			tries++;
			try {
				if (key != null) {
					clusterManager.getJedis().del(key);
				}
				sucess = true;
			} catch (JedisClusterMaxRedirectionsException | JedisConnectionException e) {
				log.error("Jedis connection failed, retrying..." + tries);
				waitforFailover();
			}
		} while (!sucess && tries <= numRetries);
	}

	/*
	 * method to wait for cluster fails
	 */
	private void waitforFailover() {
		try {
			Thread.sleep(4000);
		} catch (InterruptedException ex) {
			Thread.currentThread().interrupt();
		}
	}
}

The property isClusterEnabled should set default vlaue true;
private boolean isClusterEnabled = true;

**Comment by ran-jit** [comment]
Hello @wushuicheng 

Now, I have removed 'isClusterEnabled' variable. and updated the jar

Thanks !!
